### ISSUE TITLE
Kernel Dies on Start

### ISSUE THREAD

**Issue by sterlinm** [Calysto/matlab_kernel#4]
I have pymatbridge working on windows, but every time I try to create a notebook with the Matlab kernel it dies immediately and prompts for a manual restart that fails (this is on Windows).

**Comment by blink1073** [comment]
Hi @sterlinm, when you use `pymatbridge`, do you have to specify the Matlab executable, or is it available as "Matlab" from cmd.exe?

What version of pymatbridge are you using?

Finally, you may want to try changing this [line](https://github.com/Calysto/matlab_kernel/blob/master/matlab_kernel.py#L24) to say `_first=False`, in case there is something going on with the modifying of the plot settings.

**Comment by blink1073** [comment]
I will also say that I only have Matlab for Linux, so I'll help as I can but I'm stabbing in the dark.  :smile:

**Comment by patricksnape** [comment]
I was experiencing the same thing, but fixed it in the following ways:

  1. `pip` install this package
  2. `pip` install `metakernel` `pymatbridge` `ipython[all]`
  3. Use the [`patchelf`](http://nixos.org/patchelf.html) utility to resolve the missing shared libraries in the `messenger.mex64` library. `messenger.mex64` has been built to assume that `libmx.so` `libmex.so` and `libzmq.so.3` are all relative to the library. Therefore, you can use `patchelf` in order to add the necessary `RPATH` hooks so that the library paths can be found at runtime. You can make sure this has worked properly by using the [`ldd`](http://unixhelp.ed.ac.uk/CGI/man-cgi?ldd+1) tool, which will report `Not Found` for the three libraries until you properly set the `RPATH`. Once set correctly, `ldd` will report the location of the libraries.

I personally use `conda` for my Python dependencies, and if you do too, the `patchelf` command will look something like:

 ```
/path/to/conda/bin/patchelf --set-rpath "\$ORIGIN/../../../../../lib:/usr/local/MATLAB/R2014b/bin/glnxa64" /path/to/conda/envs/envname/lib/python2.7/site-packages/pymatbridge/matlab/messenger.mexa64
```

**Comment by patricksnape** [comment]
Just a note, on Windows you are probably having the same issue. Use [Dependency Walker](http://www.dependencywalker.com/) to see if `messenger.mexw64` is reporting any missing DLLs. Probably it will not be able to find `libzmq.dll` or `libmex.dll`. Therefore, on Windows, you probably want to update your path so that it contains the location of the Matlab `bin` folder and the location of wherever IPython installed ZMQ.

If you use conda, as mentioned above, you can put the your library folders on your path.

**Comment by sterlinm** [comment]
Thanks! I didn't realize that installing the matlab_kernel didn't install metakernel for me.
