### ISSUE TITLE
Installing MATLAB Engine for python 3.5

### ISSUE THREAD

**Issue by btaidm** [Calysto/matlab_kernel#64]
I don't know if this the right place to ask this, but I am trying to install the matlab engine on arch linux, and the has python 3.5 installed while the engine supports only up to 3.4, and errors when installing using Mathworks instructions.

How did people get around this?

Thanks

**Comment by anntzer** [comment]
Easiest right now would be to just stick to Py3.4 (via a venv or a conda env).  Note that due to the way kernels and venvs work, you only need to install the kernel (and its dependencies) in a Py3.4 env; the notebook itself can run from a 3.5 env (e.g. the default Arch install).

Depending on the MATLAB license you have access to, you may also be able to obtain the MATLAB 2016b prerelease, which supports Py3.5.

**Comment by btaidm** [comment]
Thanks

**Comment by RoyiAvital** [comment]
Wouldn't a `conda` package will make using `env` easier?

**Comment by anntzer** [comment]
No, you can just as well use pip in a conda env.
